-- begin CEMTN_TELEPHONE_NUMBER
alter table CEMTN_TELEPHONE_NUMBER add constraint FK_CEMTN_TELEPHONE_NUMBER_CUSTOMER foreign key (CUSTOMER_ID) references CEMTN_CUSTOMER(ID)^
create index IDX_CEMTN_TELEPHONE_NUMBER_CUSTOMER on CEMTN_TELEPHONE_NUMBER (CUSTOMER_ID)^
-- end CEMTN_TELEPHONE_NUMBER
